
seed: 0

dataset:
  root: 'data/CarModel'

model:
  # network
  latent_size: 128
  num_layers: 2
  message_passing_steps: 15

  # input/output
  node_feat_size: 3     # load
  edge_feat_size: 4     # 3D coord world pos + length
  output_feat_size: 1   # mises

load_model: '1.8-0.2/ckpt/2400.pkl'