
seed: 0

dataset:
  root: 'data/CarModel/test'

model: # 8 2 3
  # network
  latent_size: 16
  num_layers: 3
  message_passing_steps: 4

  # input/output
  node_feat_size: 3     # load
  edge_feat_size: 5     # 3D coord world pos + length + wind
  output_feat_size: 1   # mises

batch_size: 1
last_epoch: -1
max_epoch: 50
lr: 0.00001
decayRate: 0.9999995394830874
eval_steps: 1
save_steps: 100
log_root: 'log'
ckpt_root: 'ckpt'